/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Requirement = IDL.Record({
  'panelSize' : IDL.Text,
  'notes' : IDL.Text,
  'estimatedValue' : IDL.Nat,
  'systemType' : IDL.Text,
});
export const Time = IDL.Int;
export const PipelineStage = IDL.Variant({
  'closedWon' : IDL.Null,
  'inquiry' : IDL.Null,
  'bookingConfirmed' : IDL.Null,
  'surveyScheduled' : IDL.Null,
  'quotationSent' : IDL.Null,
  'installation' : IDL.Null,
  'closedLost' : IDL.Null,
});
export const Remark = IDL.Record({
  'content' : IDL.Text,
  'addedAt' : Time,
  'addedBy' : IDL.Text,
});
export const Lead = IDL.Record({
  'id' : IDL.Nat,
  'customerName' : IDL.Text,
  'createdAt' : Time,
  'createdBy' : IDL.Text,
  'email' : IDL.Text,
  'district' : IDL.Text,
  'updatedAt' : Time,
  'stage' : PipelineStage,
  'assignedOperationsPerson' : IDL.Opt(IDL.Text),
  'address' : IDL.Text,
  'notes' : IDL.Text,
  'phone' : IDL.Text,
  'requirements' : Requirement,
  'assignedSalesPerson' : IDL.Opt(IDL.Text),
  'remarks' : IDL.Vec(Remark),
});
export const UserRole__1 = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const QuotationRequestStatus = IDL.Variant({
  'pending' : IDL.Null,
  'confirmed' : IDL.Null,
});
export const QuotationRequest = IDL.Record({
  'id' : IDL.Text,
  'status' : QuotationRequestStatus,
  'quotationRefId' : IDL.Text,
  'confirmedAt' : IDL.Opt(Time),
  'confirmedBy' : IDL.Opt(IDL.Text),
  'confirmedByName' : IDL.Opt(IDL.Text),
  'leadId' : IDL.Nat,
  'requestedByName' : IDL.Text,
  'requestedAt' : Time,
  'requestedBy' : IDL.Text,
});
export const QuotationItem = IDL.Record({
  'description' : IDL.Text,
  'itemName' : IDL.Text,
  'quantity' : IDL.Float64,
  'unitPrice' : IDL.Float64,
});
export const QuotationInput = IDL.Record({
  'customerName' : IDL.Text,
  'panelCapacity' : IDL.Float64,
  'gstPercent' : IDL.Float64,
  'validityDays' : IDL.Nat,
  'customerAddress' : IDL.Text,
  'notes' : IDL.Text,
  'items' : IDL.Vec(QuotationItem),
  'systemType' : IDL.Text,
});
export const QuotationStatus = IDL.Variant({
  'sent' : IDL.Null,
  'rejected' : IDL.Null,
  'accepted' : IDL.Null,
  'draft' : IDL.Null,
});
export const Quotation = IDL.Record({
  'id' : IDL.Text,
  'customerName' : IDL.Text,
  'status' : QuotationStatus,
  'panelCapacity' : IDL.Float64,
  'createdAt' : Time,
  'createdBy' : IDL.Text,
  'gstPercent' : IDL.Float64,
  'validityDays' : IDL.Nat,
  'gstAmount' : IDL.Float64,
  'updatedAt' : Time,
  'customerAddress' : IDL.Text,
  'leadId' : IDL.Text,
  'totalAmount' : IDL.Float64,
  'notes' : IDL.Text,
  'quotationNumber' : IDL.Text,
  'items' : IDL.Vec(QuotationItem),
  'subtotal' : IDL.Float64,
  'systemType' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'backoffice' : IDL.Null,
  'sales' : IDL.Null,
  'operation' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'whatsAppNumber' : IDL.Text,
  'userId' : IDL.Text,
  'name' : IDL.Text,
  'role' : UserRole,
  'isActive' : IDL.Bool,
  'email' : IDL.Text,
  'district' : IDL.Text,
  'passwordHash' : IDL.Text,
  'phone' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControl' : IDL.Func([], [], []),
  'addLead' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        Requirement,
        IDL.Text,
      ],
      [IDL.Variant({ 'ok' : Lead, 'err' : IDL.Text })],
      [],
    ),
  'addRemark' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Text],
      [IDL.Variant({ 'ok' : Lead, 'err' : IDL.Text })],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole__1], [], []),
  'assignLeadToOperations' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Text],
      [IDL.Variant({ 'ok' : Lead, 'err' : IDL.Text })],
      [],
    ),
  'assignLeadToSales' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Text],
      [IDL.Variant({ 'ok' : Lead, 'err' : IDL.Text })],
      [],
    ),
  'changePassword' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'confirmQuotationRequest' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : QuotationRequest, 'err' : IDL.Text })],
      [],
    ),
  'createQuotation' : IDL.Func(
      [IDL.Text, IDL.Text, QuotationInput],
      [IDL.Variant({ 'ok' : Quotation, 'err' : IDL.Text })],
      [],
    ),
  'createUser' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        UserRole,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
      ],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'deleteLead' : IDL.Func(
      [IDL.Text, IDL.Nat],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'deleteUser' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'getAllDistricts' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getAllLeads' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Vec(Lead), 'err' : IDL.Text })],
      ['query'],
    ),
  'getAllQuotationRequests' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Vec(QuotationRequest), 'err' : IDL.Text })],
      ['query'],
    ),
  'getAllQuotations' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Vec(Quotation), 'err' : IDL.Text })],
      ['query'],
    ),
  'getAllUsers' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Vec(UserProfile), 'err' : IDL.Text })],
      ['query'],
    ),
  'getCallerUserRole' : IDL.Func([], [UserRole__1], ['query']),
  'getLeadById' : IDL.Func(
      [IDL.Text, IDL.Nat],
      [IDL.Variant({ 'ok' : Lead, 'err' : IDL.Text })],
      ['query'],
    ),
  'getLeadsAddedToday' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text })],
      ['query'],
    ),
  'getLeadsByDistrict' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Vec(Lead), 'err' : IDL.Text })],
      ['query'],
    ),
  'getLeadsByDistrictCount' : IDL.Func(
      [IDL.Text],
      [
        IDL.Variant({
          'ok' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
          'err' : IDL.Text,
        }),
      ],
      ['query'],
    ),
  'getLeadsByStage' : IDL.Func(
      [IDL.Text, PipelineStage],
      [IDL.Variant({ 'ok' : IDL.Vec(Lead), 'err' : IDL.Text })],
      ['query'],
    ),
  'getLeadsByStageCount' : IDL.Func(
      [IDL.Text],
      [
        IDL.Variant({
          'ok' : IDL.Vec(IDL.Tuple(PipelineStage, IDL.Nat)),
          'err' : IDL.Text,
        }),
      ],
      ['query'],
    ),
  'getMyLeads' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Vec(Lead), 'err' : IDL.Text })],
      ['query'],
    ),
  'getMyProfile' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : UserProfile, 'err' : IDL.Text })],
      ['query'],
    ),
  'getPendingQuotationRequests' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Vec(QuotationRequest), 'err' : IDL.Text })],
      ['query'],
    ),
  'getQuotationById' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Opt(Quotation), 'err' : IDL.Text })],
      ['query'],
    ),
  'getQuotationsByLead' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Vec(Quotation), 'err' : IDL.Text })],
      ['query'],
    ),
  'getSalesLeadGenerationToggle' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Bool, 'err' : IDL.Text })],
      ['query'],
    ),
  'getTotalLeadsCount' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text })],
      ['query'],
    ),
  'getUserById' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : UserProfile, 'err' : IDL.Text })],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'login' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'logout' : IDL.Func([IDL.Text], [], []),
  'requestQuotation' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Text],
      [IDL.Variant({ 'ok' : QuotationRequest, 'err' : IDL.Text })],
      [],
    ),
  'seedDistricts' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'setSalesLeadGenerationToggle' : IDL.Func(
      [IDL.Text, IDL.Bool],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'updateLead' : IDL.Func(
      [
        IDL.Text,
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        Requirement,
        IDL.Text,
      ],
      [IDL.Variant({ 'ok' : Lead, 'err' : IDL.Text })],
      [],
    ),
  'updateLeadStage' : IDL.Func(
      [IDL.Text, IDL.Nat, PipelineStage, IDL.Text],
      [IDL.Variant({ 'ok' : Lead, 'err' : IDL.Text })],
      [],
    ),
  'updateQuotation' : IDL.Func(
      [IDL.Text, IDL.Text, QuotationInput],
      [IDL.Variant({ 'ok' : Quotation, 'err' : IDL.Text })],
      [],
    ),
  'updateQuotationStatus' : IDL.Func(
      [IDL.Text, IDL.Text, QuotationStatus],
      [IDL.Variant({ 'ok' : Quotation, 'err' : IDL.Text })],
      [],
    ),
  'updateUser' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Bool,
      ],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'validateSession' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Text)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Requirement = IDL.Record({
    'panelSize' : IDL.Text,
    'notes' : IDL.Text,
    'estimatedValue' : IDL.Nat,
    'systemType' : IDL.Text,
  });
  const Time = IDL.Int;
  const PipelineStage = IDL.Variant({
    'closedWon' : IDL.Null,
    'inquiry' : IDL.Null,
    'bookingConfirmed' : IDL.Null,
    'surveyScheduled' : IDL.Null,
    'quotationSent' : IDL.Null,
    'installation' : IDL.Null,
    'closedLost' : IDL.Null,
  });
  const Remark = IDL.Record({
    'content' : IDL.Text,
    'addedAt' : Time,
    'addedBy' : IDL.Text,
  });
  const Lead = IDL.Record({
    'id' : IDL.Nat,
    'customerName' : IDL.Text,
    'createdAt' : Time,
    'createdBy' : IDL.Text,
    'email' : IDL.Text,
    'district' : IDL.Text,
    'updatedAt' : Time,
    'stage' : PipelineStage,
    'assignedOperationsPerson' : IDL.Opt(IDL.Text),
    'address' : IDL.Text,
    'notes' : IDL.Text,
    'phone' : IDL.Text,
    'requirements' : Requirement,
    'assignedSalesPerson' : IDL.Opt(IDL.Text),
    'remarks' : IDL.Vec(Remark),
  });
  const UserRole__1 = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const QuotationRequestStatus = IDL.Variant({
    'pending' : IDL.Null,
    'confirmed' : IDL.Null,
  });
  const QuotationRequest = IDL.Record({
    'id' : IDL.Text,
    'status' : QuotationRequestStatus,
    'quotationRefId' : IDL.Text,
    'confirmedAt' : IDL.Opt(Time),
    'confirmedBy' : IDL.Opt(IDL.Text),
    'confirmedByName' : IDL.Opt(IDL.Text),
    'leadId' : IDL.Nat,
    'requestedByName' : IDL.Text,
    'requestedAt' : Time,
    'requestedBy' : IDL.Text,
  });
  const QuotationItem = IDL.Record({
    'description' : IDL.Text,
    'itemName' : IDL.Text,
    'quantity' : IDL.Float64,
    'unitPrice' : IDL.Float64,
  });
  const QuotationInput = IDL.Record({
    'customerName' : IDL.Text,
    'panelCapacity' : IDL.Float64,
    'gstPercent' : IDL.Float64,
    'validityDays' : IDL.Nat,
    'customerAddress' : IDL.Text,
    'notes' : IDL.Text,
    'items' : IDL.Vec(QuotationItem),
    'systemType' : IDL.Text,
  });
  const QuotationStatus = IDL.Variant({
    'sent' : IDL.Null,
    'rejected' : IDL.Null,
    'accepted' : IDL.Null,
    'draft' : IDL.Null,
  });
  const Quotation = IDL.Record({
    'id' : IDL.Text,
    'customerName' : IDL.Text,
    'status' : QuotationStatus,
    'panelCapacity' : IDL.Float64,
    'createdAt' : Time,
    'createdBy' : IDL.Text,
    'gstPercent' : IDL.Float64,
    'validityDays' : IDL.Nat,
    'gstAmount' : IDL.Float64,
    'updatedAt' : Time,
    'customerAddress' : IDL.Text,
    'leadId' : IDL.Text,
    'totalAmount' : IDL.Float64,
    'notes' : IDL.Text,
    'quotationNumber' : IDL.Text,
    'items' : IDL.Vec(QuotationItem),
    'subtotal' : IDL.Float64,
    'systemType' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'backoffice' : IDL.Null,
    'sales' : IDL.Null,
    'operation' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'whatsAppNumber' : IDL.Text,
    'userId' : IDL.Text,
    'name' : IDL.Text,
    'role' : UserRole,
    'isActive' : IDL.Bool,
    'email' : IDL.Text,
    'district' : IDL.Text,
    'passwordHash' : IDL.Text,
    'phone' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControl' : IDL.Func([], [], []),
    'addLead' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          Requirement,
          IDL.Text,
        ],
        [IDL.Variant({ 'ok' : Lead, 'err' : IDL.Text })],
        [],
      ),
    'addRemark' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Text],
        [IDL.Variant({ 'ok' : Lead, 'err' : IDL.Text })],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole__1], [], []),
    'assignLeadToOperations' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Text],
        [IDL.Variant({ 'ok' : Lead, 'err' : IDL.Text })],
        [],
      ),
    'assignLeadToSales' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Text],
        [IDL.Variant({ 'ok' : Lead, 'err' : IDL.Text })],
        [],
      ),
    'changePassword' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'confirmQuotationRequest' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : QuotationRequest, 'err' : IDL.Text })],
        [],
      ),
    'createQuotation' : IDL.Func(
        [IDL.Text, IDL.Text, QuotationInput],
        [IDL.Variant({ 'ok' : Quotation, 'err' : IDL.Text })],
        [],
      ),
    'createUser' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          UserRole,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
        ],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'deleteLead' : IDL.Func(
        [IDL.Text, IDL.Nat],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'deleteUser' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'getAllDistricts' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getAllLeads' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Vec(Lead), 'err' : IDL.Text })],
        ['query'],
      ),
    'getAllQuotationRequests' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Vec(QuotationRequest), 'err' : IDL.Text })],
        ['query'],
      ),
    'getAllQuotations' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Vec(Quotation), 'err' : IDL.Text })],
        ['query'],
      ),
    'getAllUsers' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Vec(UserProfile), 'err' : IDL.Text })],
        ['query'],
      ),
    'getCallerUserRole' : IDL.Func([], [UserRole__1], ['query']),
    'getLeadById' : IDL.Func(
        [IDL.Text, IDL.Nat],
        [IDL.Variant({ 'ok' : Lead, 'err' : IDL.Text })],
        ['query'],
      ),
    'getLeadsAddedToday' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text })],
        ['query'],
      ),
    'getLeadsByDistrict' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Vec(Lead), 'err' : IDL.Text })],
        ['query'],
      ),
    'getLeadsByDistrictCount' : IDL.Func(
        [IDL.Text],
        [
          IDL.Variant({
            'ok' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
            'err' : IDL.Text,
          }),
        ],
        ['query'],
      ),
    'getLeadsByStage' : IDL.Func(
        [IDL.Text, PipelineStage],
        [IDL.Variant({ 'ok' : IDL.Vec(Lead), 'err' : IDL.Text })],
        ['query'],
      ),
    'getLeadsByStageCount' : IDL.Func(
        [IDL.Text],
        [
          IDL.Variant({
            'ok' : IDL.Vec(IDL.Tuple(PipelineStage, IDL.Nat)),
            'err' : IDL.Text,
          }),
        ],
        ['query'],
      ),
    'getMyLeads' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Vec(Lead), 'err' : IDL.Text })],
        ['query'],
      ),
    'getMyProfile' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : UserProfile, 'err' : IDL.Text })],
        ['query'],
      ),
    'getPendingQuotationRequests' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Vec(QuotationRequest), 'err' : IDL.Text })],
        ['query'],
      ),
    'getQuotationById' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Opt(Quotation), 'err' : IDL.Text })],
        ['query'],
      ),
    'getQuotationsByLead' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Vec(Quotation), 'err' : IDL.Text })],
        ['query'],
      ),
    'getSalesLeadGenerationToggle' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Bool, 'err' : IDL.Text })],
        ['query'],
      ),
    'getTotalLeadsCount' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text })],
        ['query'],
      ),
    'getUserById' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : UserProfile, 'err' : IDL.Text })],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'login' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'logout' : IDL.Func([IDL.Text], [], []),
    'requestQuotation' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Text],
        [IDL.Variant({ 'ok' : QuotationRequest, 'err' : IDL.Text })],
        [],
      ),
    'seedDistricts' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'setSalesLeadGenerationToggle' : IDL.Func(
        [IDL.Text, IDL.Bool],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'updateLead' : IDL.Func(
        [
          IDL.Text,
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          Requirement,
          IDL.Text,
        ],
        [IDL.Variant({ 'ok' : Lead, 'err' : IDL.Text })],
        [],
      ),
    'updateLeadStage' : IDL.Func(
        [IDL.Text, IDL.Nat, PipelineStage, IDL.Text],
        [IDL.Variant({ 'ok' : Lead, 'err' : IDL.Text })],
        [],
      ),
    'updateQuotation' : IDL.Func(
        [IDL.Text, IDL.Text, QuotationInput],
        [IDL.Variant({ 'ok' : Quotation, 'err' : IDL.Text })],
        [],
      ),
    'updateQuotationStatus' : IDL.Func(
        [IDL.Text, IDL.Text, QuotationStatus],
        [IDL.Variant({ 'ok' : Quotation, 'err' : IDL.Text })],
        [],
      ),
    'updateUser' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Bool,
        ],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'validateSession' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Text)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };