/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const District = IDL.Text;
export const LeadId = IDL.Nat;
export const Time = IDL.Int;
export const UserId = IDL.Principal;
export const PipelineStage = IDL.Variant({
  'closedWon' : IDL.Null,
  'inquiry' : IDL.Null,
  'bookingConfirmed' : IDL.Null,
  'surveyScheduled' : IDL.Null,
  'installation' : IDL.Null,
  'closedLost' : IDL.Null,
});
export const Requirement = IDL.Record({
  'panelSize' : IDL.Text,
  'notes' : IDL.Text,
  'estimatedValue' : IDL.Nat,
  'systemType' : IDL.Text,
});
export const Lead = IDL.Record({
  'id' : LeadId,
  'customerName' : IDL.Text,
  'createdAt' : Time,
  'createdBy' : UserId,
  'email' : IDL.Text,
  'district' : District,
  'updatedAt' : Time,
  'stage' : PipelineStage,
  'assignedOperationsPerson' : IDL.Opt(UserId),
  'address' : IDL.Text,
  'notes' : IDL.Text,
  'phone' : IDL.Text,
  'requirements' : Requirement,
  'assignedSalesPerson' : IDL.Opt(UserId),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'sales' : IDL.Null,
  'operations' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'principal' : UserId,
  'name' : IDL.Text,
  'role' : UserRole,
  'email' : IDL.Text,
  'district' : District,
  'phone' : IDL.Text,
});
export const UserRole__1 = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ApprovalStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const UserApprovalInfo = IDL.Record({
  'status' : ApprovalStatus,
  'principal' : IDL.Principal,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addDistrict' : IDL.Func([District], [], []),
  'addLead' : IDL.Func([Lead], [LeadId], []),
  'addUserProfile' : IDL.Func([UserProfile], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole__1], [], []),
  'assignLeadToOperations' : IDL.Func([LeadId, UserId], [], []),
  'assignLeadToSales' : IDL.Func([LeadId, UserId], [], []),
  'getAllDistricts' : IDL.Func([], [IDL.Vec(District)], ['query']),
  'getAllLeads' : IDL.Func([], [IDL.Vec(Lead)], ['query']),
  'getAllUserProfiles' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole__1], ['query']),
  'getLeadById' : IDL.Func([LeadId], [IDL.Opt(Lead)], ['query']),
  'getLeadsAddedToday' : IDL.Func([], [IDL.Nat], ['query']),
  'getLeadsByDistrict' : IDL.Func([District], [IDL.Vec(Lead)], ['query']),
  'getLeadsByDistrictCount' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(District, IDL.Nat))],
      ['query'],
    ),
  'getLeadsBySalesPerson' : IDL.Func([UserId], [IDL.Vec(Lead)], ['query']),
  'getLeadsByStage' : IDL.Func([PipelineStage], [IDL.Vec(Lead)], ['query']),
  'getLeadsByStageCount' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(PipelineStage, IDL.Nat))],
      ['query'],
    ),
  'getMyLeads' : IDL.Func([], [IDL.Vec(Lead)], ['query']),
  'getTotalLeadsCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerApproved' : IDL.Func([], [IDL.Bool], ['query']),
  'listApprovals' : IDL.Func([], [IDL.Vec(UserApprovalInfo)], ['query']),
  'requestApproval' : IDL.Func([], [], []),
  'setApproval' : IDL.Func([IDL.Principal, ApprovalStatus], [], []),
  'updateLead' : IDL.Func([LeadId, Lead], [], []),
  'updateLeadStage' : IDL.Func([LeadId, PipelineStage, IDL.Text], [], []),
  'updateUserProfile' : IDL.Func([UserProfile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const District = IDL.Text;
  const LeadId = IDL.Nat;
  const Time = IDL.Int;
  const UserId = IDL.Principal;
  const PipelineStage = IDL.Variant({
    'closedWon' : IDL.Null,
    'inquiry' : IDL.Null,
    'bookingConfirmed' : IDL.Null,
    'surveyScheduled' : IDL.Null,
    'installation' : IDL.Null,
    'closedLost' : IDL.Null,
  });
  const Requirement = IDL.Record({
    'panelSize' : IDL.Text,
    'notes' : IDL.Text,
    'estimatedValue' : IDL.Nat,
    'systemType' : IDL.Text,
  });
  const Lead = IDL.Record({
    'id' : LeadId,
    'customerName' : IDL.Text,
    'createdAt' : Time,
    'createdBy' : UserId,
    'email' : IDL.Text,
    'district' : District,
    'updatedAt' : Time,
    'stage' : PipelineStage,
    'assignedOperationsPerson' : IDL.Opt(UserId),
    'address' : IDL.Text,
    'notes' : IDL.Text,
    'phone' : IDL.Text,
    'requirements' : Requirement,
    'assignedSalesPerson' : IDL.Opt(UserId),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'sales' : IDL.Null,
    'operations' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'principal' : UserId,
    'name' : IDL.Text,
    'role' : UserRole,
    'email' : IDL.Text,
    'district' : District,
    'phone' : IDL.Text,
  });
  const UserRole__1 = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ApprovalStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const UserApprovalInfo = IDL.Record({
    'status' : ApprovalStatus,
    'principal' : IDL.Principal,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addDistrict' : IDL.Func([District], [], []),
    'addLead' : IDL.Func([Lead], [LeadId], []),
    'addUserProfile' : IDL.Func([UserProfile], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole__1], [], []),
    'assignLeadToOperations' : IDL.Func([LeadId, UserId], [], []),
    'assignLeadToSales' : IDL.Func([LeadId, UserId], [], []),
    'getAllDistricts' : IDL.Func([], [IDL.Vec(District)], ['query']),
    'getAllLeads' : IDL.Func([], [IDL.Vec(Lead)], ['query']),
    'getAllUserProfiles' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole__1], ['query']),
    'getLeadById' : IDL.Func([LeadId], [IDL.Opt(Lead)], ['query']),
    'getLeadsAddedToday' : IDL.Func([], [IDL.Nat], ['query']),
    'getLeadsByDistrict' : IDL.Func([District], [IDL.Vec(Lead)], ['query']),
    'getLeadsByDistrictCount' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(District, IDL.Nat))],
        ['query'],
      ),
    'getLeadsBySalesPerson' : IDL.Func([UserId], [IDL.Vec(Lead)], ['query']),
    'getLeadsByStage' : IDL.Func([PipelineStage], [IDL.Vec(Lead)], ['query']),
    'getLeadsByStageCount' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(PipelineStage, IDL.Nat))],
        ['query'],
      ),
    'getMyLeads' : IDL.Func([], [IDL.Vec(Lead)], ['query']),
    'getTotalLeadsCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerApproved' : IDL.Func([], [IDL.Bool], ['query']),
    'listApprovals' : IDL.Func([], [IDL.Vec(UserApprovalInfo)], ['query']),
    'requestApproval' : IDL.Func([], [], []),
    'setApproval' : IDL.Func([IDL.Principal, ApprovalStatus], [], []),
    'updateLead' : IDL.Func([LeadId, Lead], [], []),
    'updateLeadStage' : IDL.Func([LeadId, PipelineStage, IDL.Text], [], []),
    'updateUserProfile' : IDL.Func([UserProfile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };