/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Lead {
  'id' : bigint,
  'customerName' : string,
  'createdAt' : Time,
  'createdBy' : string,
  'email' : string,
  'district' : string,
  'updatedAt' : Time,
  'stage' : PipelineStage,
  'assignedOperationsPerson' : [] | [string],
  'address' : string,
  'notes' : string,
  'phone' : string,
  'requirements' : Requirement,
  'assignedSalesPerson' : [] | [string],
  'remarks' : Array<Remark>,
}
export type PipelineStage = { 'closedWon' : null } |
  { 'inquiry' : null } |
  { 'bookingConfirmed' : null } |
  { 'surveyScheduled' : null } |
  { 'quotationSent' : null } |
  { 'installation' : null } |
  { 'closedLost' : null };
export interface Quotation {
  'id' : string,
  'customerName' : string,
  'status' : QuotationStatus,
  'panelCapacity' : number,
  'createdAt' : Time,
  'createdBy' : string,
  'gstPercent' : number,
  'validityDays' : bigint,
  'gstAmount' : number,
  'updatedAt' : Time,
  'customerAddress' : string,
  'leadId' : string,
  'totalAmount' : number,
  'notes' : string,
  'quotationNumber' : string,
  'items' : Array<QuotationItem>,
  'subtotal' : number,
  'systemType' : string,
}
export interface QuotationInput {
  'customerName' : string,
  'panelCapacity' : number,
  'gstPercent' : number,
  'validityDays' : bigint,
  'customerAddress' : string,
  'notes' : string,
  'items' : Array<QuotationItem>,
  'systemType' : string,
}
export interface QuotationItem {
  'description' : string,
  'itemName' : string,
  'quantity' : number,
  'unitPrice' : number,
}
export interface QuotationRequest {
  'id' : string,
  'status' : QuotationRequestStatus,
  'quotationRefId' : string,
  'confirmedAt' : [] | [Time],
  'confirmedBy' : [] | [string],
  'confirmedByName' : [] | [string],
  'leadId' : bigint,
  'requestedByName' : string,
  'requestedAt' : Time,
  'requestedBy' : string,
}
export type QuotationRequestStatus = { 'pending' : null } |
  { 'confirmed' : null };
export type QuotationStatus = { 'sent' : null } |
  { 'rejected' : null } |
  { 'accepted' : null } |
  { 'draft' : null };
export interface Remark {
  'content' : string,
  'addedAt' : Time,
  'addedBy' : string,
}
export interface Requirement {
  'panelSize' : string,
  'notes' : string,
  'estimatedValue' : bigint,
  'systemType' : string,
}
export type Time = bigint;
export interface UserProfile {
  'whatsAppNumber' : string,
  'userId' : string,
  'name' : string,
  'role' : UserRole,
  'isActive' : boolean,
  'email' : string,
  'district' : string,
  'passwordHash' : string,
  'phone' : string,
}
export type UserRole = { 'admin' : null } |
  { 'backoffice' : null } |
  { 'sales' : null } |
  { 'operation' : null };
export type UserRole__1 = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'addLead' : ActorMethod<
    [
      string,
      string,
      string,
      string,
      string,
      string,
      Requirement,
      string,
      [] | [string],
    ],
    { 'ok' : Lead } |
      { 'err' : string }
  >,
  'addRemark' : ActorMethod<
    [string, bigint, string],
    { 'ok' : Lead } |
      { 'err' : string }
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole__1], undefined>,
  'assignLeadToOperations' : ActorMethod<
    [string, bigint, string],
    { 'ok' : Lead } |
      { 'err' : string }
  >,
  'assignLeadToSales' : ActorMethod<
    [string, bigint, string],
    { 'ok' : Lead } |
      { 'err' : string }
  >,
  'changePassword' : ActorMethod<
    [string, string, string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  /**
   * / Backoffice/admin confirms a quotation request. Sets status to #confirmed,
   * / moves the lead to #quotationSent, and adds a remark.
   */
  'confirmQuotationRequest' : ActorMethod<
    [string, string],
    { 'ok' : QuotationRequest } |
      { 'err' : string }
  >,
  'createQuotation' : ActorMethod<
    [string, string, QuotationInput],
    { 'ok' : Quotation } |
      { 'err' : string }
  >,
  'createUser' : ActorMethod<
    [string, string, string, string, UserRole, string, string, string, string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'deleteLead' : ActorMethod<
    [string, bigint],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'deleteUser' : ActorMethod<
    [string, string],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'getAllDistricts' : ActorMethod<[], Array<string>>,
  'getAllLeads' : ActorMethod<
    [string],
    { 'ok' : Array<Lead> } |
      { 'err' : string }
  >,
  /**
   * / Returns all QuotationRequests regardless of status. Accessible by backoffice and admin.
   */
  'getAllQuotationRequests' : ActorMethod<
    [string],
    { 'ok' : Array<QuotationRequest> } |
      { 'err' : string }
  >,
  'getAllQuotations' : ActorMethod<
    [string],
    { 'ok' : Array<Quotation> } |
      { 'err' : string }
  >,
  'getAllUsers' : ActorMethod<
    [string],
    { 'ok' : Array<UserProfile> } |
      { 'err' : string }
  >,
  'getCallerUserRole' : ActorMethod<[], UserRole__1>,
  'getLeadById' : ActorMethod<
    [string, bigint],
    { 'ok' : Lead } |
      { 'err' : string }
  >,
  'getLeadsAddedToday' : ActorMethod<
    [string],
    { 'ok' : bigint } |
      { 'err' : string }
  >,
  'getLeadsByDistrict' : ActorMethod<
    [string, string],
    { 'ok' : Array<Lead> } |
      { 'err' : string }
  >,
  'getLeadsByDistrictCount' : ActorMethod<
    [string],
    { 'ok' : Array<[string, bigint]> } |
      { 'err' : string }
  >,
  'getLeadsByStage' : ActorMethod<
    [string, PipelineStage],
    { 'ok' : Array<Lead> } |
      { 'err' : string }
  >,
  'getLeadsByStageCount' : ActorMethod<
    [string],
    { 'ok' : Array<[PipelineStage, bigint]> } |
      { 'err' : string }
  >,
  'getMyLeads' : ActorMethod<
    [string],
    { 'ok' : Array<Lead> } |
      { 'err' : string }
  >,
  'getMyProfile' : ActorMethod<
    [string],
    { 'ok' : UserProfile } |
      { 'err' : string }
  >,
  /**
   * / Returns all QuotationRequests with #pending status. Accessible by backoffice and admin.
   */
  'getPendingQuotationRequests' : ActorMethod<
    [string],
    { 'ok' : Array<QuotationRequest> } |
      { 'err' : string }
  >,
  'getQuotationById' : ActorMethod<
    [string, string],
    { 'ok' : [] | [Quotation] } |
      { 'err' : string }
  >,
  'getQuotationsByLead' : ActorMethod<
    [string, string],
    { 'ok' : Array<Quotation> } |
      { 'err' : string }
  >,
  /**
   * / Returns the current value of the sales lead generation toggle.
   * / Any authenticated user can read this.
   */
  'getSalesLeadGenerationToggle' : ActorMethod<
    [string],
    { 'ok' : boolean } |
      { 'err' : string }
  >,
  'getTotalLeadsCount' : ActorMethod<
    [string],
    { 'ok' : bigint } |
      { 'err' : string }
  >,
  'getUserById' : ActorMethod<
    [string, string],
    { 'ok' : UserProfile } |
      { 'err' : string }
  >,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'login' : ActorMethod<
    [string, string],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'logout' : ActorMethod<[string], undefined>,
  /**
   * / Sales requests a quotation for a lead. Creates a QuotationRequest with #pending status.
   * / Does NOT change the lead stage. Adds a remark to the lead.
   */
  'requestQuotation' : ActorMethod<
    [string, bigint, string],
    { 'ok' : QuotationRequest } |
      { 'err' : string }
  >,
  'seedDistricts' : ActorMethod<[], Array<string>>,
  /**
   * / Admin-only: enable or disable sales staff from creating and self-assigning their own leads.
   */
  'setSalesLeadGenerationToggle' : ActorMethod<
    [string, boolean],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'updateLead' : ActorMethod<
    [
      string,
      bigint,
      string,
      string,
      string,
      string,
      string,
      Requirement,
      string,
      [] | [string],
    ],
    { 'ok' : Lead } |
      { 'err' : string }
  >,
  'updateLeadStage' : ActorMethod<
    [string, bigint, PipelineStage, string],
    { 'ok' : Lead } |
      { 'err' : string }
  >,
  'updateQuotation' : ActorMethod<
    [string, string, QuotationInput],
    { 'ok' : Quotation } |
      { 'err' : string }
  >,
  'updateQuotationStatus' : ActorMethod<
    [string, string, QuotationStatus],
    { 'ok' : Quotation } |
      { 'err' : string }
  >,
  'updateUser' : ActorMethod<
    [string, string, string, string, string, string, string, boolean],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'validateSession' : ActorMethod<[string], [] | [string]>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];