/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ApprovalStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export type District = string;
export interface Lead {
  'id' : LeadId,
  'customerName' : string,
  'createdAt' : Time,
  'createdBy' : UserId,
  'email' : string,
  'district' : District,
  'updatedAt' : Time,
  'stage' : PipelineStage,
  'assignedOperationsPerson' : [] | [UserId],
  'address' : string,
  'notes' : string,
  'phone' : string,
  'requirements' : Requirement,
  'assignedSalesPerson' : [] | [UserId],
}
export type LeadId = bigint;
export type PipelineStage = { 'closedWon' : null } |
  { 'inquiry' : null } |
  { 'bookingConfirmed' : null } |
  { 'surveyScheduled' : null } |
  { 'installation' : null } |
  { 'closedLost' : null };
export interface Requirement {
  'panelSize' : string,
  'notes' : string,
  'estimatedValue' : bigint,
  'systemType' : string,
}
export type Time = bigint;
export interface UserApprovalInfo {
  'status' : ApprovalStatus,
  'principal' : Principal,
}
export type UserId = Principal;
export interface UserProfile {
  'principal' : UserId,
  'name' : string,
  'role' : UserRole,
  'email' : string,
  'district' : District,
  'phone' : string,
}
export type UserRole = { 'admin' : null } |
  { 'sales' : null } |
  { 'operations' : null };
export type UserRole__1 = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addDistrict' : ActorMethod<[District], undefined>,
  'addLead' : ActorMethod<[Lead], LeadId>,
  'addUserProfile' : ActorMethod<[UserProfile], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole__1], undefined>,
  'assignLeadToOperations' : ActorMethod<[LeadId, UserId], undefined>,
  'assignLeadToSales' : ActorMethod<[LeadId, UserId], undefined>,
  'getAllDistricts' : ActorMethod<[], Array<District>>,
  'getAllLeads' : ActorMethod<[], Array<Lead>>,
  'getAllUserProfiles' : ActorMethod<[], Array<UserProfile>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole__1>,
  'getLeadById' : ActorMethod<[LeadId], [] | [Lead]>,
  'getLeadsAddedToday' : ActorMethod<[], bigint>,
  'getLeadsByDistrict' : ActorMethod<[District], Array<Lead>>,
  'getLeadsByDistrictCount' : ActorMethod<[], Array<[District, bigint]>>,
  'getLeadsBySalesPerson' : ActorMethod<[UserId], Array<Lead>>,
  'getLeadsByStage' : ActorMethod<[PipelineStage], Array<Lead>>,
  'getLeadsByStageCount' : ActorMethod<[], Array<[PipelineStage, bigint]>>,
  'getMyLeads' : ActorMethod<[], Array<Lead>>,
  'getTotalLeadsCount' : ActorMethod<[], bigint>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isCallerApproved' : ActorMethod<[], boolean>,
  'listApprovals' : ActorMethod<[], Array<UserApprovalInfo>>,
  'requestApproval' : ActorMethod<[], undefined>,
  'setApproval' : ActorMethod<[Principal, ApprovalStatus], undefined>,
  'updateLead' : ActorMethod<[LeadId, Lead], undefined>,
  'updateLeadStage' : ActorMethod<[LeadId, PipelineStage, string], undefined>,
  'updateUserProfile' : ActorMethod<[UserProfile], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];