/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Lead {
    id: bigint;
    customerName: string;
    createdAt: Time;
    createdBy: string;
    email: string;
    district: string;
    updatedAt: Time;
    stage: PipelineStage;
    assignedOperationsPerson?: string;
    address: string;
    notes: string;
    phone: string;
    requirements: Requirement;
    assignedSalesPerson?: string;
    remarks: Array<Remark>;
}
export interface QuotationItem {
    description: string;
    itemName: string;
    quantity: number;
    unitPrice: number;
}
export type Time = bigint;
export interface Requirement {
    panelSize: string;
    notes: string;
    estimatedValue: bigint;
    systemType: string;
}
export interface QuotationInput {
    customerName: string;
    panelCapacity: number;
    gstPercent: number;
    validityDays: bigint;
    customerAddress: string;
    notes: string;
    items: Array<QuotationItem>;
    systemType: string;
}
export interface Remark {
    content: string;
    addedAt: Time;
    addedBy: string;
}
export interface Quotation {
    id: string;
    customerName: string;
    status: QuotationStatus;
    panelCapacity: number;
    createdAt: Time;
    createdBy: string;
    gstPercent: number;
    validityDays: bigint;
    gstAmount: number;
    updatedAt: Time;
    customerAddress: string;
    leadId: string;
    totalAmount: number;
    notes: string;
    quotationNumber: string;
    items: Array<QuotationItem>;
    subtotal: number;
    systemType: string;
}
export interface UserProfile {
    whatsAppNumber: string;
    userId: string;
    name: string;
    role: UserRole;
    isActive: boolean;
    email: string;
    district: string;
    passwordHash: string;
    phone: string;
}
export enum PipelineStage {
    closedWon = "closedWon",
    inquiry = "inquiry",
    bookingConfirmed = "bookingConfirmed",
    surveyScheduled = "surveyScheduled",
    quotationSent = "quotationSent",
    installation = "installation",
    closedLost = "closedLost"
}
export enum QuotationStatus {
    sent = "sent",
    rejected = "rejected",
    accepted = "accepted",
    draft = "draft"
}
export enum UserRole {
    admin = "admin",
    backoffice = "backoffice",
    sales = "sales",
    operation = "operation"
}
export enum UserRole__1 {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControl(): Promise<void>;
    addLead(sessionToken: string, customerName: string, phone: string, email: string, address: string, district: string, requirements: Requirement, notes: string): Promise<{
        __kind__: "ok";
        ok: Lead;
    } | {
        __kind__: "err";
        err: string;
    }>;
    addRemark(sessionToken: string, leadId: bigint, content: string): Promise<{
        __kind__: "ok";
        ok: Lead;
    } | {
        __kind__: "err";
        err: string;
    }>;
    assignCallerUserRole(user: Principal, role: UserRole__1): Promise<void>;
    assignLeadToOperations(sessionToken: string, leadId: bigint, operationsUserId: string): Promise<{
        __kind__: "ok";
        ok: Lead;
    } | {
        __kind__: "err";
        err: string;
    }>;
    assignLeadToSales(sessionToken: string, leadId: bigint, salesUserId: string): Promise<{
        __kind__: "ok";
        ok: Lead;
    } | {
        __kind__: "err";
        err: string;
    }>;
    changePassword(sessionToken: string, userId: string, newPassword: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    createQuotation(sessionToken: string, leadId: string, data: QuotationInput): Promise<{
        __kind__: "ok";
        ok: Quotation;
    } | {
        __kind__: "err";
        err: string;
    }>;
    createUser(sessionToken: string, userId: string, password: string, name: string, role: UserRole, district: string, phone: string, email: string, whatsAppNumber: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    deleteLead(sessionToken: string, leadId: bigint): Promise<{
        __kind__: "ok";
        ok: string;
    } | {
        __kind__: "err";
        err: string;
    }>;
    deleteUser(sessionToken: string, userId: string): Promise<{
        __kind__: "ok";
        ok: string;
    } | {
        __kind__: "err";
        err: string;
    }>;
    getAllDistricts(): Promise<Array<string>>;
    getAllLeads(sessionToken: string): Promise<{
        __kind__: "ok";
        ok: Array<Lead>;
    } | {
        __kind__: "err";
        err: string;
    }>;
    getAllQuotations(sessionToken: string): Promise<{
        __kind__: "ok";
        ok: Array<Quotation>;
    } | {
        __kind__: "err";
        err: string;
    }>;
    getAllUsers(sessionToken: string): Promise<{
        __kind__: "ok";
        ok: Array<UserProfile>;
    } | {
        __kind__: "err";
        err: string;
    }>;
    getCallerUserRole(): Promise<UserRole__1>;
    getLeadById(sessionToken: string, leadId: bigint): Promise<{
        __kind__: "ok";
        ok: Lead;
    } | {
        __kind__: "err";
        err: string;
    }>;
    getLeadsAddedToday(sessionToken: string): Promise<{
        __kind__: "ok";
        ok: bigint;
    } | {
        __kind__: "err";
        err: string;
    }>;
    getLeadsByDistrict(sessionToken: string, district: string): Promise<{
        __kind__: "ok";
        ok: Array<Lead>;
    } | {
        __kind__: "err";
        err: string;
    }>;
    getLeadsByDistrictCount(sessionToken: string): Promise<{
        __kind__: "ok";
        ok: Array<[string, bigint]>;
    } | {
        __kind__: "err";
        err: string;
    }>;
    getLeadsByStage(sessionToken: string, stage: PipelineStage): Promise<{
        __kind__: "ok";
        ok: Array<Lead>;
    } | {
        __kind__: "err";
        err: string;
    }>;
    getLeadsByStageCount(sessionToken: string): Promise<{
        __kind__: "ok";
        ok: Array<[PipelineStage, bigint]>;
    } | {
        __kind__: "err";
        err: string;
    }>;
    getMyLeads(sessionToken: string): Promise<{
        __kind__: "ok";
        ok: Array<Lead>;
    } | {
        __kind__: "err";
        err: string;
    }>;
    getMyProfile(sessionToken: string): Promise<{
        __kind__: "ok";
        ok: UserProfile;
    } | {
        __kind__: "err";
        err: string;
    }>;
    getQuotationById(sessionToken: string, id: string): Promise<{
        __kind__: "ok";
        ok: Quotation | null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    getQuotationsByLead(sessionToken: string, leadId: string): Promise<{
        __kind__: "ok";
        ok: Array<Quotation>;
    } | {
        __kind__: "err";
        err: string;
    }>;
    getTotalLeadsCount(sessionToken: string): Promise<{
        __kind__: "ok";
        ok: bigint;
    } | {
        __kind__: "err";
        err: string;
    }>;
    getUserById(sessionToken: string, userId: string): Promise<{
        __kind__: "ok";
        ok: UserProfile;
    } | {
        __kind__: "err";
        err: string;
    }>;
    isCallerAdmin(): Promise<boolean>;
    login(username: string, password: string): Promise<{
        __kind__: "ok";
        ok: string;
    } | {
        __kind__: "err";
        err: string;
    }>;
    logout(sessionToken: string): Promise<void>;
    seedDistricts(): Promise<Array<string>>;
    updateLead(sessionToken: string, leadId: bigint, customerName: string, phone: string, email: string, address: string, district: string, requirements: Requirement, notes: string): Promise<{
        __kind__: "ok";
        ok: Lead;
    } | {
        __kind__: "err";
        err: string;
    }>;
    updateLeadStage(sessionToken: string, leadId: bigint, stage: PipelineStage, notes: string): Promise<{
        __kind__: "ok";
        ok: Lead;
    } | {
        __kind__: "err";
        err: string;
    }>;
    updateQuotation(sessionToken: string, id: string, data: QuotationInput): Promise<{
        __kind__: "ok";
        ok: Quotation;
    } | {
        __kind__: "err";
        err: string;
    }>;
    updateQuotationStatus(sessionToken: string, id: string, status: QuotationStatus): Promise<{
        __kind__: "ok";
        ok: Quotation;
    } | {
        __kind__: "err";
        err: string;
    }>;
    updateUser(sessionToken: string, userId: string, name: string, district: string, phone: string, email: string, whatsAppNumber: string, isActive: boolean): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    validateSession(sessionToken: string): Promise<string | null>;
}
import type { Lead as _Lead, PipelineStage as _PipelineStage, Quotation as _Quotation, QuotationItem as _QuotationItem, QuotationStatus as _QuotationStatus, Remark as _Remark, Requirement as _Requirement, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole, UserRole__1 as _UserRole__1 } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControl();
            return result;
        }
    }
    async addLead(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string, arg5: string, arg6: Requirement, arg7: string): Promise<{
        __kind__: "ok";
        ok: Lead;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.addLead(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
                return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addLead(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
            return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async addRemark(arg0: string, arg1: bigint, arg2: string): Promise<{
        __kind__: "ok";
        ok: Lead;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.addRemark(arg0, arg1, arg2);
                return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addRemark(arg0, arg1, arg2);
            return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole__1): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole__1_n7(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole__1_n7(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async assignLeadToOperations(arg0: string, arg1: bigint, arg2: string): Promise<{
        __kind__: "ok";
        ok: Lead;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.assignLeadToOperations(arg0, arg1, arg2);
                return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignLeadToOperations(arg0, arg1, arg2);
            return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async assignLeadToSales(arg0: string, arg1: bigint, arg2: string): Promise<{
        __kind__: "ok";
        ok: Lead;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.assignLeadToSales(arg0, arg1, arg2);
                return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignLeadToSales(arg0, arg1, arg2);
            return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async changePassword(arg0: string, arg1: string, arg2: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.changePassword(arg0, arg1, arg2);
                return from_candid_variant_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.changePassword(arg0, arg1, arg2);
            return from_candid_variant_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async createQuotation(arg0: string, arg1: string, arg2: QuotationInput): Promise<{
        __kind__: "ok";
        ok: Quotation;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.createQuotation(arg0, arg1, arg2);
                return from_candid_variant_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createQuotation(arg0, arg1, arg2);
            return from_candid_variant_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async createUser(arg0: string, arg1: string, arg2: string, arg3: string, arg4: UserRole, arg5: string, arg6: string, arg7: string, arg8: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.createUser(arg0, arg1, arg2, arg3, to_candid_UserRole_n15(this._uploadFile, this._downloadFile, arg4), arg5, arg6, arg7, arg8);
                return from_candid_variant_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createUser(arg0, arg1, arg2, arg3, to_candid_UserRole_n15(this._uploadFile, this._downloadFile, arg4), arg5, arg6, arg7, arg8);
            return from_candid_variant_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteLead(arg0: string, arg1: bigint): Promise<{
        __kind__: "ok";
        ok: string;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteLead(arg0, arg1);
                return from_candid_variant_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteLead(arg0, arg1);
            return from_candid_variant_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteUser(arg0: string, arg1: string): Promise<{
        __kind__: "ok";
        ok: string;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteUser(arg0, arg1);
                return from_candid_variant_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteUser(arg0, arg1);
            return from_candid_variant_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllDistricts(): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllDistricts();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllDistricts();
            return result;
        }
    }
    async getAllLeads(arg0: string): Promise<{
        __kind__: "ok";
        ok: Array<Lead>;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllLeads(arg0);
                return from_candid_variant_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllLeads(arg0);
            return from_candid_variant_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllQuotations(arg0: string): Promise<{
        __kind__: "ok";
        ok: Array<Quotation>;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllQuotations(arg0);
                return from_candid_variant_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllQuotations(arg0);
            return from_candid_variant_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllUsers(arg0: string): Promise<{
        __kind__: "ok";
        ok: Array<UserProfile>;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllUsers(arg0);
                return from_candid_variant_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllUsers(arg0);
            return from_candid_variant_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole__1> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole__1_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole__1_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLeadById(arg0: string, arg1: bigint): Promise<{
        __kind__: "ok";
        ok: Lead;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getLeadById(arg0, arg1);
                return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLeadById(arg0, arg1);
            return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLeadsAddedToday(arg0: string): Promise<{
        __kind__: "ok";
        ok: bigint;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getLeadsAddedToday(arg0);
                return from_candid_variant_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLeadsAddedToday(arg0);
            return from_candid_variant_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLeadsByDistrict(arg0: string, arg1: string): Promise<{
        __kind__: "ok";
        ok: Array<Lead>;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getLeadsByDistrict(arg0, arg1);
                return from_candid_variant_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLeadsByDistrict(arg0, arg1);
            return from_candid_variant_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLeadsByDistrictCount(arg0: string): Promise<{
        __kind__: "ok";
        ok: Array<[string, bigint]>;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getLeadsByDistrictCount(arg0);
                return from_candid_variant_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLeadsByDistrictCount(arg0);
            return from_candid_variant_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLeadsByStage(arg0: string, arg1: PipelineStage): Promise<{
        __kind__: "ok";
        ok: Array<Lead>;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getLeadsByStage(arg0, to_candid_PipelineStage_n32(this._uploadFile, this._downloadFile, arg1));
                return from_candid_variant_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLeadsByStage(arg0, to_candid_PipelineStage_n32(this._uploadFile, this._downloadFile, arg1));
            return from_candid_variant_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLeadsByStageCount(arg0: string): Promise<{
        __kind__: "ok";
        ok: Array<[PipelineStage, bigint]>;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getLeadsByStageCount(arg0);
                return from_candid_variant_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLeadsByStageCount(arg0);
            return from_candid_variant_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyLeads(arg0: string): Promise<{
        __kind__: "ok";
        ok: Array<Lead>;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyLeads(arg0);
                return from_candid_variant_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyLeads(arg0);
            return from_candid_variant_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyProfile(arg0: string): Promise<{
        __kind__: "ok";
        ok: UserProfile;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyProfile(arg0);
                return from_candid_variant_n37(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyProfile(arg0);
            return from_candid_variant_n37(this._uploadFile, this._downloadFile, result);
        }
    }
    async getQuotationById(arg0: string, arg1: string): Promise<{
        __kind__: "ok";
        ok: Quotation | null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getQuotationById(arg0, arg1);
                return from_candid_variant_n38(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getQuotationById(arg0, arg1);
            return from_candid_variant_n38(this._uploadFile, this._downloadFile, result);
        }
    }
    async getQuotationsByLead(arg0: string, arg1: string): Promise<{
        __kind__: "ok";
        ok: Array<Quotation>;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getQuotationsByLead(arg0, arg1);
                return from_candid_variant_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getQuotationsByLead(arg0, arg1);
            return from_candid_variant_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTotalLeadsCount(arg0: string): Promise<{
        __kind__: "ok";
        ok: bigint;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getTotalLeadsCount(arg0);
                return from_candid_variant_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTotalLeadsCount(arg0);
            return from_candid_variant_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserById(arg0: string, arg1: string): Promise<{
        __kind__: "ok";
        ok: UserProfile;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserById(arg0, arg1);
                return from_candid_variant_n37(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserById(arg0, arg1);
            return from_candid_variant_n37(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async login(arg0: string, arg1: string): Promise<{
        __kind__: "ok";
        ok: string;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.login(arg0, arg1);
                return from_candid_variant_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.login(arg0, arg1);
            return from_candid_variant_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async logout(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.logout(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.logout(arg0);
            return result;
        }
    }
    async seedDistricts(): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.seedDistricts();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.seedDistricts();
            return result;
        }
    }
    async updateLead(arg0: string, arg1: bigint, arg2: string, arg3: string, arg4: string, arg5: string, arg6: string, arg7: Requirement, arg8: string): Promise<{
        __kind__: "ok";
        ok: Lead;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.updateLead(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
                return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateLead(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
            return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateLeadStage(arg0: string, arg1: bigint, arg2: PipelineStage, arg3: string): Promise<{
        __kind__: "ok";
        ok: Lead;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.updateLeadStage(arg0, arg1, to_candid_PipelineStage_n32(this._uploadFile, this._downloadFile, arg2), arg3);
                return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateLeadStage(arg0, arg1, to_candid_PipelineStage_n32(this._uploadFile, this._downloadFile, arg2), arg3);
            return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateQuotation(arg0: string, arg1: string, arg2: QuotationInput): Promise<{
        __kind__: "ok";
        ok: Quotation;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.updateQuotation(arg0, arg1, arg2);
                return from_candid_variant_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateQuotation(arg0, arg1, arg2);
            return from_candid_variant_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateQuotationStatus(arg0: string, arg1: string, arg2: QuotationStatus): Promise<{
        __kind__: "ok";
        ok: Quotation;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.updateQuotationStatus(arg0, arg1, to_candid_QuotationStatus_n40(this._uploadFile, this._downloadFile, arg2));
                return from_candid_variant_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateQuotationStatus(arg0, arg1, to_candid_QuotationStatus_n40(this._uploadFile, this._downloadFile, arg2));
            return from_candid_variant_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateUser(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string, arg5: string, arg6: string, arg7: boolean): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.updateUser(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
                return from_candid_variant_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateUser(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
            return from_candid_variant_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async validateSession(arg0: string): Promise<string | null> {
        if (this.processError) {
            try {
                const result = await this.actor.validateSession(arg0);
                return from_candid_opt_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.validateSession(arg0);
            return from_candid_opt_n6(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_Lead_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Lead): Lead {
    return from_candid_record_n3(_uploadFile, _downloadFile, value);
}
function from_candid_PipelineStage_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PipelineStage): PipelineStage {
    return from_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function from_candid_QuotationStatus_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _QuotationStatus): QuotationStatus {
    return from_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function from_candid_Quotation_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Quotation): Quotation {
    return from_candid_record_n12(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n25(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole__1_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole__1): UserRole__1 {
    return from_candid_variant_n29(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n27(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Quotation]): Quotation | null {
    return value.length === 0 ? null : from_candid_Quotation_n11(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    customerName: string;
    status: _QuotationStatus;
    panelCapacity: number;
    createdAt: _Time;
    createdBy: string;
    gstPercent: number;
    validityDays: bigint;
    gstAmount: number;
    updatedAt: _Time;
    customerAddress: string;
    leadId: string;
    totalAmount: number;
    notes: string;
    quotationNumber: string;
    items: Array<_QuotationItem>;
    subtotal: number;
    systemType: string;
}): {
    id: string;
    customerName: string;
    status: QuotationStatus;
    panelCapacity: number;
    createdAt: Time;
    createdBy: string;
    gstPercent: number;
    validityDays: bigint;
    gstAmount: number;
    updatedAt: Time;
    customerAddress: string;
    leadId: string;
    totalAmount: number;
    notes: string;
    quotationNumber: string;
    items: Array<QuotationItem>;
    subtotal: number;
    systemType: string;
} {
    return {
        id: value.id,
        customerName: value.customerName,
        status: from_candid_QuotationStatus_n13(_uploadFile, _downloadFile, value.status),
        panelCapacity: value.panelCapacity,
        createdAt: value.createdAt,
        createdBy: value.createdBy,
        gstPercent: value.gstPercent,
        validityDays: value.validityDays,
        gstAmount: value.gstAmount,
        updatedAt: value.updatedAt,
        customerAddress: value.customerAddress,
        leadId: value.leadId,
        totalAmount: value.totalAmount,
        notes: value.notes,
        quotationNumber: value.quotationNumber,
        items: value.items,
        subtotal: value.subtotal,
        systemType: value.systemType
    };
}
function from_candid_record_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    whatsAppNumber: string;
    userId: string;
    name: string;
    role: _UserRole;
    isActive: boolean;
    email: string;
    district: string;
    passwordHash: string;
    phone: string;
}): {
    whatsAppNumber: string;
    userId: string;
    name: string;
    role: UserRole;
    isActive: boolean;
    email: string;
    district: string;
    passwordHash: string;
    phone: string;
} {
    return {
        whatsAppNumber: value.whatsAppNumber,
        userId: value.userId,
        name: value.name,
        role: from_candid_UserRole_n26(_uploadFile, _downloadFile, value.role),
        isActive: value.isActive,
        email: value.email,
        district: value.district,
        passwordHash: value.passwordHash,
        phone: value.phone
    };
}
function from_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    customerName: string;
    createdAt: _Time;
    createdBy: string;
    email: string;
    district: string;
    updatedAt: _Time;
    stage: _PipelineStage;
    assignedOperationsPerson: [] | [string];
    address: string;
    notes: string;
    phone: string;
    requirements: _Requirement;
    assignedSalesPerson: [] | [string];
    remarks: Array<_Remark>;
}): {
    id: bigint;
    customerName: string;
    createdAt: Time;
    createdBy: string;
    email: string;
    district: string;
    updatedAt: Time;
    stage: PipelineStage;
    assignedOperationsPerson?: string;
    address: string;
    notes: string;
    phone: string;
    requirements: Requirement;
    assignedSalesPerson?: string;
    remarks: Array<Remark>;
} {
    return {
        id: value.id,
        customerName: value.customerName,
        createdAt: value.createdAt,
        createdBy: value.createdBy,
        email: value.email,
        district: value.district,
        updatedAt: value.updatedAt,
        stage: from_candid_PipelineStage_n4(_uploadFile, _downloadFile, value.stage),
        assignedOperationsPerson: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.assignedOperationsPerson)),
        address: value.address,
        notes: value.notes,
        phone: value.phone,
        requirements: value.requirements,
        assignedSalesPerson: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.assignedSalesPerson)),
        remarks: value.remarks
    };
}
function from_candid_tuple_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [_PipelineStage, bigint]): [PipelineStage, bigint] {
    return [
        from_candid_PipelineStage_n4(_uploadFile, _downloadFile, value[0]),
        value[1]
    ];
}
function from_candid_variant_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _Lead;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: Lead;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_Lead_n2(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _Quotation;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: Quotation;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_Quotation_n11(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    sent: null;
} | {
    rejected: null;
} | {
    accepted: null;
} | {
    draft: null;
}): QuotationStatus {
    return "sent" in value ? QuotationStatus.sent : "rejected" in value ? QuotationStatus.rejected : "accepted" in value ? QuotationStatus.accepted : "draft" in value ? QuotationStatus.draft : value;
}
function from_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: string;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: string;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: Array<_Lead>;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: Array<Lead>;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_vec_n19(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: Array<_Quotation>;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: Array<Quotation>;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_vec_n21(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: Array<_UserProfile>;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: Array<UserProfile>;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_vec_n23(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    backoffice: null;
} | {
    sales: null;
} | {
    operation: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "backoffice" in value ? UserRole.backoffice : "sales" in value ? UserRole.sales : "operation" in value ? UserRole.operation : value;
}
function from_candid_variant_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole__1 {
    return "admin" in value ? UserRole__1.admin : "user" in value ? UserRole__1.user : "guest" in value ? UserRole__1.guest : value;
}
function from_candid_variant_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: bigint;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: bigint;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: Array<[string, bigint]>;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: Array<[string, bigint]>;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: Array<[_PipelineStage, bigint]>;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: Array<[PipelineStage, bigint]>;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_vec_n35(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _UserProfile;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: UserProfile;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_UserProfile_n24(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: [] | [_Quotation];
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: Quotation | null;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_opt_n39(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    closedWon: null;
} | {
    inquiry: null;
} | {
    bookingConfirmed: null;
} | {
    surveyScheduled: null;
} | {
    quotationSent: null;
} | {
    installation: null;
} | {
    closedLost: null;
}): PipelineStage {
    return "closedWon" in value ? PipelineStage.closedWon : "inquiry" in value ? PipelineStage.inquiry : "bookingConfirmed" in value ? PipelineStage.bookingConfirmed : "surveyScheduled" in value ? PipelineStage.surveyScheduled : "quotationSent" in value ? PipelineStage.quotationSent : "installation" in value ? PipelineStage.installation : "closedLost" in value ? PipelineStage.closedLost : value;
}
function from_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_vec_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Lead>): Array<Lead> {
    return value.map((x)=>from_candid_Lead_n2(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Quotation>): Array<Quotation> {
    return value.map((x)=>from_candid_Quotation_n11(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_UserProfile>): Array<UserProfile> {
    return value.map((x)=>from_candid_UserProfile_n24(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[_PipelineStage, bigint]>): Array<[PipelineStage, bigint]> {
    return value.map((x)=>from_candid_tuple_n36(_uploadFile, _downloadFile, x));
}
function to_candid_PipelineStage_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PipelineStage): _PipelineStage {
    return to_candid_variant_n33(_uploadFile, _downloadFile, value);
}
function to_candid_QuotationStatus_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: QuotationStatus): _QuotationStatus {
    return to_candid_variant_n41(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole__1_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole__1): _UserRole__1 {
    return to_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    backoffice: null;
} | {
    sales: null;
} | {
    operation: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.backoffice ? {
        backoffice: null
    } : value == UserRole.sales ? {
        sales: null
    } : value == UserRole.operation ? {
        operation: null
    } : value;
}
function to_candid_variant_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PipelineStage): {
    closedWon: null;
} | {
    inquiry: null;
} | {
    bookingConfirmed: null;
} | {
    surveyScheduled: null;
} | {
    quotationSent: null;
} | {
    installation: null;
} | {
    closedLost: null;
} {
    return value == PipelineStage.closedWon ? {
        closedWon: null
    } : value == PipelineStage.inquiry ? {
        inquiry: null
    } : value == PipelineStage.bookingConfirmed ? {
        bookingConfirmed: null
    } : value == PipelineStage.surveyScheduled ? {
        surveyScheduled: null
    } : value == PipelineStage.quotationSent ? {
        quotationSent: null
    } : value == PipelineStage.installation ? {
        installation: null
    } : value == PipelineStage.closedLost ? {
        closedLost: null
    } : value;
}
function to_candid_variant_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: QuotationStatus): {
    sent: null;
} | {
    rejected: null;
} | {
    accepted: null;
} | {
    draft: null;
} {
    return value == QuotationStatus.sent ? {
        sent: null
    } : value == QuotationStatus.rejected ? {
        rejected: null
    } : value == QuotationStatus.accepted ? {
        accepted: null
    } : value == QuotationStatus.draft ? {
        draft: null
    } : value;
}
function to_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole__1): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole__1.admin ? {
        admin: null
    } : value == UserRole__1.user ? {
        user: null
    } : value == UserRole__1.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
