/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Lead {
    id: LeadId;
    customerName: string;
    createdAt: Time;
    createdBy: UserId;
    email: string;
    district: District;
    updatedAt: Time;
    stage: PipelineStage;
    assignedOperationsPerson?: UserId;
    address: string;
    notes: string;
    phone: string;
    requirements: Requirement;
    assignedSalesPerson?: UserId;
}
export type UserId = Principal;
export interface UserApprovalInfo {
    status: ApprovalStatus;
    principal: Principal;
}
export type Time = bigint;
export interface Requirement {
    panelSize: string;
    notes: string;
    estimatedValue: bigint;
    systemType: string;
}
export type LeadId = bigint;
export type District = string;
export interface UserProfile {
    principal: UserId;
    name: string;
    role: UserRole;
    email: string;
    district: District;
    phone: string;
}
export enum ApprovalStatus {
    pending = "pending",
    approved = "approved",
    rejected = "rejected"
}
export enum PipelineStage {
    closedWon = "closedWon",
    inquiry = "inquiry",
    bookingConfirmed = "bookingConfirmed",
    surveyScheduled = "surveyScheduled",
    installation = "installation",
    closedLost = "closedLost"
}
export enum UserRole {
    admin = "admin",
    sales = "sales",
    operations = "operations"
}
export enum UserRole__1 {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControl(): Promise<void>;
    addDistrict(district: District): Promise<void>;
    addLead(input: Lead): Promise<LeadId>;
    addUserProfile(profile: UserProfile): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole__1): Promise<void>;
    assignLeadToOperations(leadId: LeadId, operationsPerson: UserId): Promise<void>;
    assignLeadToSales(leadId: LeadId, salesPerson: UserId): Promise<void>;
    getAllDistricts(): Promise<Array<District>>;
    getAllLeads(): Promise<Array<Lead>>;
    getAllUserProfiles(): Promise<Array<UserProfile>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole__1>;
    getLeadById(leadId: LeadId): Promise<Lead | null>;
    getLeadsAddedToday(): Promise<bigint>;
    getLeadsByDistrict(district: District): Promise<Array<Lead>>;
    getLeadsByDistrictCount(): Promise<Array<[District, bigint]>>;
    getLeadsBySalesPerson(salesPerson: UserId): Promise<Array<Lead>>;
    getLeadsByStage(stage: PipelineStage): Promise<Array<Lead>>;
    getLeadsByStageCount(): Promise<Array<[PipelineStage, bigint]>>;
    getMyLeads(): Promise<Array<Lead>>;
    getTotalLeadsCount(): Promise<bigint>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    isCallerApproved(): Promise<boolean>;
    listApprovals(): Promise<Array<UserApprovalInfo>>;
    requestApproval(): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    setApproval(user: Principal, status: ApprovalStatus): Promise<void>;
    updateLead(leadId: LeadId, input: Lead): Promise<void>;
    updateLeadStage(leadId: LeadId, stage: PipelineStage, notes: string): Promise<void>;
    updateUserProfile(profile: UserProfile): Promise<void>;
}
import type { ApprovalStatus as _ApprovalStatus, District as _District, Lead as _Lead, LeadId as _LeadId, PipelineStage as _PipelineStage, Requirement as _Requirement, Time as _Time, UserApprovalInfo as _UserApprovalInfo, UserId as _UserId, UserProfile as _UserProfile, UserRole as _UserRole, UserRole__1 as _UserRole__1 } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControl();
            return result;
        }
    }
    async addDistrict(arg0: District): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addDistrict(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addDistrict(arg0);
            return result;
        }
    }
    async addLead(arg0: Lead): Promise<LeadId> {
        if (this.processError) {
            try {
                const result = await this.actor.addLead(to_candid_Lead_n1(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addLead(to_candid_Lead_n1(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addUserProfile(to_candid_UserProfile_n5(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addUserProfile(to_candid_UserProfile_n5(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole__1): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole__1_n9(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole__1_n9(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async assignLeadToOperations(arg0: LeadId, arg1: UserId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignLeadToOperations(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignLeadToOperations(arg0, arg1);
            return result;
        }
    }
    async assignLeadToSales(arg0: LeadId, arg1: UserId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignLeadToSales(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignLeadToSales(arg0, arg1);
            return result;
        }
    }
    async getAllDistricts(): Promise<Array<District>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllDistricts();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllDistricts();
            return result;
        }
    }
    async getAllLeads(): Promise<Array<Lead>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllLeads();
                return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllLeads();
            return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllUserProfiles(): Promise<Array<UserProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllUserProfiles();
                return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllUserProfiles();
            return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole__1> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole__1_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole__1_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLeadById(arg0: LeadId): Promise<Lead | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getLeadById(arg0);
                return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLeadById(arg0);
            return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLeadsAddedToday(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getLeadsAddedToday();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLeadsAddedToday();
            return result;
        }
    }
    async getLeadsByDistrict(arg0: District): Promise<Array<Lead>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLeadsByDistrict(arg0);
                return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLeadsByDistrict(arg0);
            return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLeadsByDistrictCount(): Promise<Array<[District, bigint]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLeadsByDistrictCount();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLeadsByDistrictCount();
            return result;
        }
    }
    async getLeadsBySalesPerson(arg0: UserId): Promise<Array<Lead>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLeadsBySalesPerson(arg0);
                return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLeadsBySalesPerson(arg0);
            return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLeadsByStage(arg0: PipelineStage): Promise<Array<Lead>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLeadsByStage(to_candid_PipelineStage_n3(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLeadsByStage(to_candid_PipelineStage_n3(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLeadsByStageCount(): Promise<Array<[PipelineStage, bigint]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLeadsByStageCount();
                return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLeadsByStageCount();
            return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyLeads(): Promise<Array<Lead>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyLeads();
                return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyLeads();
            return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTotalLeadsCount(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getTotalLeadsCount();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTotalLeadsCount();
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isCallerApproved(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerApproved();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerApproved();
            return result;
        }
    }
    async listApprovals(): Promise<Array<UserApprovalInfo>> {
        if (this.processError) {
            try {
                const result = await this.actor.listApprovals();
                return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listApprovals();
            return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async requestApproval(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.requestApproval();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.requestApproval();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n5(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n5(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async setApproval(arg0: Principal, arg1: ApprovalStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setApproval(arg0, to_candid_ApprovalStatus_n33(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setApproval(arg0, to_candid_ApprovalStatus_n33(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateLead(arg0: LeadId, arg1: Lead): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateLead(arg0, to_candid_Lead_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateLead(arg0, to_candid_Lead_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateLeadStage(arg0: LeadId, arg1: PipelineStage, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateLeadStage(arg0, to_candid_PipelineStage_n3(this._uploadFile, this._downloadFile, arg1), arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateLeadStage(arg0, to_candid_PipelineStage_n3(this._uploadFile, this._downloadFile, arg1), arg2);
            return result;
        }
    }
    async updateUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateUserProfile(to_candid_UserProfile_n5(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateUserProfile(to_candid_UserProfile_n5(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
}
function from_candid_ApprovalStatus_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ApprovalStatus): ApprovalStatus {
    return from_candid_variant_n32(_uploadFile, _downloadFile, value);
}
function from_candid_Lead_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Lead): Lead {
    return from_candid_record_n13(_uploadFile, _downloadFile, value);
}
function from_candid_PipelineStage_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PipelineStage): PipelineStage {
    return from_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function from_candid_UserApprovalInfo_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserApprovalInfo): UserApprovalInfo {
    return from_candid_record_n30(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n19(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole__1_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole__1): UserRole__1 {
    return from_candid_variant_n24(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n21(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserId]): UserId | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n18(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Lead]): Lead | null {
    return value.length === 0 ? null : from_candid_Lead_n12(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _LeadId;
    customerName: string;
    createdAt: _Time;
    createdBy: _UserId;
    email: string;
    district: _District;
    updatedAt: _Time;
    stage: _PipelineStage;
    assignedOperationsPerson: [] | [_UserId];
    address: string;
    notes: string;
    phone: string;
    requirements: _Requirement;
    assignedSalesPerson: [] | [_UserId];
}): {
    id: LeadId;
    customerName: string;
    createdAt: Time;
    createdBy: UserId;
    email: string;
    district: District;
    updatedAt: Time;
    stage: PipelineStage;
    assignedOperationsPerson?: UserId;
    address: string;
    notes: string;
    phone: string;
    requirements: Requirement;
    assignedSalesPerson?: UserId;
} {
    return {
        id: value.id,
        customerName: value.customerName,
        createdAt: value.createdAt,
        createdBy: value.createdBy,
        email: value.email,
        district: value.district,
        updatedAt: value.updatedAt,
        stage: from_candid_PipelineStage_n14(_uploadFile, _downloadFile, value.stage),
        assignedOperationsPerson: record_opt_to_undefined(from_candid_opt_n16(_uploadFile, _downloadFile, value.assignedOperationsPerson)),
        address: value.address,
        notes: value.notes,
        phone: value.phone,
        requirements: value.requirements,
        assignedSalesPerson: record_opt_to_undefined(from_candid_opt_n16(_uploadFile, _downloadFile, value.assignedSalesPerson))
    };
}
function from_candid_record_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    principal: _UserId;
    name: string;
    role: _UserRole;
    email: string;
    district: _District;
    phone: string;
}): {
    principal: UserId;
    name: string;
    role: UserRole;
    email: string;
    district: District;
    phone: string;
} {
    return {
        principal: value.principal,
        name: value.name,
        role: from_candid_UserRole_n20(_uploadFile, _downloadFile, value.role),
        email: value.email,
        district: value.district,
        phone: value.phone
    };
}
function from_candid_record_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _ApprovalStatus;
    principal: Principal;
}): {
    status: ApprovalStatus;
    principal: Principal;
} {
    return {
        status: from_candid_ApprovalStatus_n31(_uploadFile, _downloadFile, value.status),
        principal: value.principal
    };
}
function from_candid_tuple_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [_PipelineStage, bigint]): [PipelineStage, bigint] {
    return [
        from_candid_PipelineStage_n14(_uploadFile, _downloadFile, value[0]),
        value[1]
    ];
}
function from_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    closedWon: null;
} | {
    inquiry: null;
} | {
    bookingConfirmed: null;
} | {
    surveyScheduled: null;
} | {
    installation: null;
} | {
    closedLost: null;
}): PipelineStage {
    return "closedWon" in value ? PipelineStage.closedWon : "inquiry" in value ? PipelineStage.inquiry : "bookingConfirmed" in value ? PipelineStage.bookingConfirmed : "surveyScheduled" in value ? PipelineStage.surveyScheduled : "installation" in value ? PipelineStage.installation : "closedLost" in value ? PipelineStage.closedLost : value;
}
function from_candid_variant_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    sales: null;
} | {
    operations: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "sales" in value ? UserRole.sales : "operations" in value ? UserRole.operations : value;
}
function from_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole__1 {
    return "admin" in value ? UserRole__1.admin : "user" in value ? UserRole__1.user : "guest" in value ? UserRole__1.guest : value;
}
function from_candid_variant_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
}): ApprovalStatus {
    return "pending" in value ? ApprovalStatus.pending : "approved" in value ? ApprovalStatus.approved : "rejected" in value ? ApprovalStatus.rejected : value;
}
function from_candid_vec_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Lead>): Array<Lead> {
    return value.map((x)=>from_candid_Lead_n12(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_UserProfile>): Array<UserProfile> {
    return value.map((x)=>from_candid_UserProfile_n18(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[_PipelineStage, bigint]>): Array<[PipelineStage, bigint]> {
    return value.map((x)=>from_candid_tuple_n27(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_UserApprovalInfo>): Array<UserApprovalInfo> {
    return value.map((x)=>from_candid_UserApprovalInfo_n29(_uploadFile, _downloadFile, x));
}
function to_candid_ApprovalStatus_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ApprovalStatus): _ApprovalStatus {
    return to_candid_variant_n34(_uploadFile, _downloadFile, value);
}
function to_candid_Lead_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Lead): _Lead {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_PipelineStage_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PipelineStage): _PipelineStage {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n6(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole__1_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole__1): _UserRole__1 {
    return to_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: LeadId;
    customerName: string;
    createdAt: Time;
    createdBy: UserId;
    email: string;
    district: District;
    updatedAt: Time;
    stage: PipelineStage;
    assignedOperationsPerson?: UserId;
    address: string;
    notes: string;
    phone: string;
    requirements: Requirement;
    assignedSalesPerson?: UserId;
}): {
    id: _LeadId;
    customerName: string;
    createdAt: _Time;
    createdBy: _UserId;
    email: string;
    district: _District;
    updatedAt: _Time;
    stage: _PipelineStage;
    assignedOperationsPerson: [] | [_UserId];
    address: string;
    notes: string;
    phone: string;
    requirements: _Requirement;
    assignedSalesPerson: [] | [_UserId];
} {
    return {
        id: value.id,
        customerName: value.customerName,
        createdAt: value.createdAt,
        createdBy: value.createdBy,
        email: value.email,
        district: value.district,
        updatedAt: value.updatedAt,
        stage: to_candid_PipelineStage_n3(_uploadFile, _downloadFile, value.stage),
        assignedOperationsPerson: value.assignedOperationsPerson ? candid_some(value.assignedOperationsPerson) : candid_none(),
        address: value.address,
        notes: value.notes,
        phone: value.phone,
        requirements: value.requirements,
        assignedSalesPerson: value.assignedSalesPerson ? candid_some(value.assignedSalesPerson) : candid_none()
    };
}
function to_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    principal: UserId;
    name: string;
    role: UserRole;
    email: string;
    district: District;
    phone: string;
}): {
    principal: _UserId;
    name: string;
    role: _UserRole;
    email: string;
    district: _District;
    phone: string;
} {
    return {
        principal: value.principal,
        name: value.name,
        role: to_candid_UserRole_n7(_uploadFile, _downloadFile, value.role),
        email: value.email,
        district: value.district,
        phone: value.phone
    };
}
function to_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole__1): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole__1.admin ? {
        admin: null
    } : value == UserRole__1.user ? {
        user: null
    } : value == UserRole__1.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ApprovalStatus): {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
} {
    return value == ApprovalStatus.pending ? {
        pending: null
    } : value == ApprovalStatus.approved ? {
        approved: null
    } : value == ApprovalStatus.rejected ? {
        rejected: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PipelineStage): {
    closedWon: null;
} | {
    inquiry: null;
} | {
    bookingConfirmed: null;
} | {
    surveyScheduled: null;
} | {
    installation: null;
} | {
    closedLost: null;
} {
    return value == PipelineStage.closedWon ? {
        closedWon: null
    } : value == PipelineStage.inquiry ? {
        inquiry: null
    } : value == PipelineStage.bookingConfirmed ? {
        bookingConfirmed: null
    } : value == PipelineStage.surveyScheduled ? {
        surveyScheduled: null
    } : value == PipelineStage.installation ? {
        installation: null
    } : value == PipelineStage.closedLost ? {
        closedLost: null
    } : value;
}
function to_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    sales: null;
} | {
    operations: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.sales ? {
        sales: null
    } : value == UserRole.operations ? {
        operations: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
